### PR TITLE
Add support for geometry columns

### PR DESCRIPTION
**Pull request by zhm**
This PR adds support for parsing native PostGIS geometries instead of latitude & longitude columns. The net result is that you can now display polygons on the map, e.g. `ST_Buffer` results. It also switches over to using the JSON output format so it can access the column metadata to find the geometry column. It uses the first geometry column in the result set as the geometry to use on the map view.

### CODE REVIEW

**Comment by zhm** [comment]
Perhaps it could fallback to looking for `latitude` & `longitude` also. Not sure which cases you would reasonable have a `latitude` and `longitude` but not a real geom, but it's possible.

**Comment by bmcbride** [comment]
This is pretty awesome! I initially went with the CSV format to keep the request payloads as small as possible, but this may be a good reason to switch over to JSON.

**Comment by rylincoln** [comment]
FWIW - I switched over to zhm's branch and haven't noticed any performance differences. :+1:

**Comment by zhm** [comment]
The geometry format was changed from WKT to GeoJSON fragments so that consumers don't need a WKT parser to make sense of the output. The patch is in 9892e208877f3b4ff4a8e0c777b4d544601f9c48.

**Pull request merged**
